### ISSUE TITLE
Elm UI with Tachyons

### ISSUE THREAD

**Issue by nelsonic** [dwyl/hapi-socketio-redis-chat-example#86]
@finnhodgkin & @ZooeyMiller 

# TODO:

+ [x] Go through this tutorial and confirm you:
  + [x] Run the code on your `localhost`
  + [x] Test it on your mobile device connecting to your `localhost`
  + [x] Understand the code & tests (ask any questions if anything unclear)
+ [x] Create an endpoint for rendering the Elm UI
+ [x] Re-create the _current_ UI in Elm and Tachyons
+ [x] Hook up UI to Hapi Backend

**Comment by ZooeyMiller** [comment]
Thanks @nelsonic, @finnhodgkin and I are running through the tutorial now, will update here.
We don't have write access to this repo so will need that before we can assign ourselves etc.

**Comment by nelsonic** [comment]
@ZooeyMiller / @finnhodgkin `if` after reading the readme and skimming the code you are unable to get it working on your laptop, please let me know so we can pair on it this afternoon. thanks!

**Comment by finnhodgkin** [comment]
@nelsonic We pomodoro'd and I compared the code to some socket stuff I've done before and we're still stuck :man_shrugging: 

Think we've found where the problem is.. Just not what's causing it. ___Help?___

**Comment by ZooeyMiller** [comment]
Just checked out the live one on heroku and seems to not be working there either at the moment...

**Comment by finnhodgkin** [comment]
Well it's now working on my comp. I just deleted the `socket.io` and `socket.io-client` entries from `package.json` and reinstalled them (npm i...)

Didn't work for Zooey's...

**Comment by ZooeyMiller** [comment]
Seems the problems we are having are related to versioning, similar to #69.
We changed socket.io version to 1.7.3 and socket.io-client to 2.0.3 and it started working. Have to make sure to delete package-lock.json before installing it seems.

**Comment by finnhodgkin** [comment]
For the '<user> has joined the channel' feature, do we want to re-implement this exactly the same in elm, or do we want an online/offline user list? In terms of complexity they're pretty much the same.

**Comment by ZooeyMiller** [comment]
We've gotten the UI close to what is in the original version, the only bit we're still doing is making the `<user> has joined the room` notification pop up.

**Comment by nelsonic** [comment]
@ZooeyMiller please see: https://github.com/dwyl/chat/issues/38 (_confirm if criteria is sufficient_)

**Comment by ZooeyMiller** [comment]
We've made a "user has joined the room" notification which appears in the chat log, the idea would be that this notification appears when a user joins/leaves but does not persist either through local storage or redis.

We decided to use localstorage for storing the user's name as it seems to play nicer with elm than cookies do.

**Comment by ZooeyMiller** [comment]
Having completed the initial UI with Elm we're now working on hooking up our Elm front end to the back end which is already in place. (This may involve very minor modifications to the back end code, but hopefully not). 

As discussed in #93 we have decided to carry on with socket.io and the back end as it stands right now. 

As of right now we have got our elm front end to send out a message when a new user joins, and you can send messages from our FE to the chat (which appears on the non-elm FE).

See following comment for list of things to do

**Comment by ZooeyMiller** [comment]
- [x] emit user joined when someone joins Elm FE
- [x] send message from Elm FE
- [ ] get message history from BE into Elm FE
- [ ] display new messages in Elm FE
- [ ] tinker with back end to get 'user joined' message to play nicely with our Elm FE
- [ ] document experiences with making Elm FE for chat app
- [ ]  test Elm code
- [ ] test JS code (the ports stuff)

**Comment by ZooeyMiller** [comment]
Currently working on doing the HTTP request to get the message history into our app, but having a bit of trouble with decoding the result.

**Comment by ZooeyMiller** [comment]
We've now added the functionality to scroll to the bottom on new messages, so the majority of the functionality is there! 
We need to work on error handling (at the moment we do deal with all possibilities, but sometimes not in a very meaningful way), testing an documentation.

**Comment by finnhodgkin** [comment]
We've added a few unit tests to the easier functions (parseTimestamp, parseMessage and view).

Now we're testing the decoders by passing in fake JSON strings. 

Writing tests in Elm is sweet! :smiley:

**Comment by finnhodgkin** [comment]
@nelsonic We don't have 100% 'test coverage' of the Elm app, but everything not covered (non-logic stuff) is covered by the Elm compiler. Is this an appropriate way to write tests for Elm or should we be replicating our efforts from last week even in Elm?

**Comment by ZooeyMiller** [comment]
We are now at a point of doing minor tweaks on the Elm front end including informative error messages. 
Tomorrow we hope to work on documentation and then remove the [WiP] from our PR!

**Comment by ZooeyMiller** [comment]
We are now working on making sure Elm can never get a runtime error due to getting the wrong data type from javascript (through ports). 
In theory we should always be getting a string through the port to Elm because we send it directly from the socket without tinkering in JS at all, so it _should_ always be a string. But we all know never to trust javascript, so using a bit of TDD we are checking all basic data types are dealt with and accounted for.

**Comment by ZooeyMiller** [comment]
@nelsonic we've now got a working, commented and tested Elm front end done :tada: 
The code is commented such that (to us) what it is doing and how it is doing it is clear (to someone who knows Elm). We do still need to add how to run the Elm version locally to the README.md.
Do you think we should add more documentation than the code comments, or do you think it's sufficiently explained as is?

**Comment by nelsonic** [comment]
This PR #91 has now been merged. 🎉
