### ISSUE TITLE
Epic: creating dwylchat

### ISSUE THREAD

**Issue by ZooeyMiller** [dwyl/hapi-socketio-redis-chat-example#96]
As explained in: https://github.com/dwyl/chat/issues/41 we are creating the front end (as much as we can) for dwylchat in this repo. We have created a staging branch to make PRs to so that we can create feature branches off of the staging branch and PR back to it, to have as good of a workflow as possible.

So we need to list what we need to do:
- [ ] Initial design of the chat
- [ ] Component: online users widget
- [ ] Component: actual chat (input and message list)
- [ ] Component: room/type of chat list 
- [ ] Feature: Store chat history locally and update with call to back end for list of messages. 
- [ ] Feature: Scroll chat down so new messages stay in view when scrolled to bottom, maintain scroll position if scrolled further up
- [ ] Feature: Notify user when new messages are available

(more to be added as we think of them)

**Comment by ZooeyMiller** [comment]
(as not to overwhelm the repo we are going to raise individual issues for each item in here as an when we start working on them)
